import * as fs from "fs";import * as path from "path";
const authority=require("../scripts/lib/architecture-authority");const api=require("../scripts/lib/public-api");const dist=require("../scripts/lib/dist-integrity");
describe("architecture authority",()=>{
 test("active authority and schemas validate",()=>{expect(authority.validateAuthorityDocument(authority.readJson(path.join(process.cwd(),"docs/architecture-authority.json")))).toEqual([]);expect(authority.validateAuthoritySchemaDocument(authority.readJson(path.join(process.cwd(),"docs/schemas/architecture-authority.schema.json")))).toEqual([]);});
 test("traceability and legacy archive validate",()=>{expect(authority.validateTraceabilityDocument(authority.readJson(path.join(process.cwd(),"docs/traceability-map.json")))).toEqual([]);expect(authority.verifyLegacyArchive(process.cwd())).toEqual([]);});
 test("API and package contracts validate",()=>{const contract=authority.readJson(path.join(process.cwd(),"docs/public-api-contract.json"));const pkg=authority.readJson(path.join(process.cwd(),"package.json"));expect(api.validateContract(contract,process.cwd())).toEqual([]);expect(api.validatePackageAgainstContract(pkg,contract)).toEqual([]);expect(dist.validatePackageContract(authority.readJson(path.join(process.cwd(),"docs/package-contract.json")))).toEqual([]);});
 test("manifest inventory contains API boundary",()=>{const paths=authority.AUTHORITY_CRITICAL_PATHS;for(const rel of ["src/index.ts","src/public/inventory.ts","src/public/schema.ts","src/public/advanced.ts","src/public/llm.ts","docs/public-api-contract.json","scripts/check-public-api.js","tests/public_api_runtime.test.ts"])expect(paths).toContain(rel);});
 test("active docs do not revive the legacy plane",()=>{for(const rel of ["docs/contracts.md","docs/decision_log.md","docs/manifest.md","docs/public-api.md"]){const text=fs.readFileSync(path.join(process.cwd(),rel),"utf8");expect(text).not.toMatch(/consolidate_request|move_map\.csv|L9_ARTIFACT_META|folder_artifact_consolidation/i);}});
});
