import * as root from "../src/index";
import * as inventory from "../src/public/inventory";
import * as schema from "../src/public/schema";
import * as advanced from "../src/public/advanced";
import * as llm from "../src/public/llm";
const expected={
 root:["assertAuthorityForOperation","buildCarrierOperationPlan","CANONICAL_METADATA_WRITER","inlinePlanDrift","isAuthorityConfig","isPromptMeta","isSupportedAuthoritySchema","LEGACY_OPERATION_ALIASES","META_AUTHORITY_SCHEMA","META_V3_PLANES","META_V3_SCHEMA_VERSION","metadataIndexDrift","OPERATION_MODES","operationRequiresAuthority","planCarrierOperationAsync","PRIMITIVE_TAXONOMY","resolveOperationMode","runApplyAsync","runCheckAsync","runPipelineAsync","runSkillsPipelineAsync","UNKNOWN"],
 inventory:["buildDuplicateClusters","buildRecord","classifyInventory","inventoryTree","loadMetaSchema"],
 schema:["asRecord","assertAuthorityForOperation","buildMetaV3","coerceNormalizedMeta","hasAllPlanes","isAuthorityConfig","isPromptMeta","isSupportedAuthoritySchema","LEGACY_OPERATION_ALIASES","META_AUTHORITY_SCHEMA","META_V3_PLANES","META_V3_SCHEMA_VERSION","normalizeMetaRecord","OPERATION_MODES","operationRequiresAuthority","PRIMITIVE_TAXONOMY","resolveOperationMode","UNKNOWN"],
 advanced:["acquireLocalSource","applyCommentInjection","applySchema","ARCHIVE_MEMBER_SEPARATOR","assertCarrierDecisionCoverage","assistField","buildCarrierOperationPlan","buildDedupEntries","buildDedupReport","buildLocalSourceManifest","buildMeta","buildOmitMatcher","buildPrimitiveLibraryIndex","buildPromptLibraryIndex","BUILTIN_NOISE_PATTERNS","BUILTIN_SKILL_PROTECT_PATTERNS","canonicalBlockReason","canonicalMemberPath","CARRIER_PRECEDENCE","CLASS_PLACEMENT_HINTS","classify","classifyArtifact","classifyWithSemantics","compileMetadataIndex","compilePlacementPlan","compilePlacementPlans","contentHash","dedupReportToMarkdown","DEFAULT_ASSIST_CONFIG","DEFAULT_LOCAL_ARCHIVE_POLICY","diffsToLogYaml","ENCODING_CHUNK_BYTES","estimateTokens","executeFileTransaction","extract","extractInjectedYaml","FILE_TRANSACTION_SCHEMA","findFiles","FRONTMATTER_EXTS","FRONTMATTER_PATCH_SCHEMA","frontMatterInner","GENERATED_ARTIFACT_OMIT_PATTERNS","GRAMMAR_ORIGIN_FIELDS","hashFileStreaming","hasInjectedBlock","hasLegacyExtractionOwnership","hasUseWhenSignal","injectFile","injectFileAsync","INLINE_MANAGED_ARTIFACT_TYPES","inlinePlanDrift","inspectFrontMatterDocument","isDecodableText","isGoodValue","isLegacyGeneratedExtraction","isProbablyBinary","isSemanticArtifactClass","isSkillArtifactPath","isSkillMdBasename","L9_METAIGNORE_FILENAME","LEGACY_EXTRACTION_OWNER_FILE","LEGACY_EXTRACTION_SUFFIX","LOCAL_ARCHIVE_POLICY_VERSION","LOCAL_SOURCE_MANIFEST_SCHEMA","memberCollisionKey","METADATA_INDEX_RELATIVE_PATH","METADATA_INDEX_SCHEMA","metadataIndexDrift","normalizeFilename","normalizeFilenames","normalizeFilenameWithLog","observeLocalSourceModel","parseCanonicalYaml","parseMetadataIndex","patchManagedFrontMatter","physicalManifestDigest","placementHintFor","planCarrierOperationAsync","preflightArchive","probeBufferEncoding","probeFileEncoding","PROSE_ORIGIN_FIELDS","QUARANTINE_DIRECTORY","readUtf8Strict","reconcileFields","reconcileFieldsAsync","recoverPendingTransactions","resolveCarrierDecision","resolveCarrierDecisions","resolveLocalArchivePolicy","resolveNamespace","resolveStrategy","scanFiles","SCRATCH_OWNER_FILE","SCRATCH_OWNER_ID","SEMANTIC_ARTIFACT_CLASSES","serializeMetadataIndex","serializeToYamlFrontMatter","sidecarPathFor","splitContent","stripExistingFrontMatter","stripInjectedBlock","targetIncludes","toMetaSchema","toRepositoryModelLocalSource","toSnakeCase","toSnakeStem","TRANSACTION_DIRECTORY","verify","withLocalSourceModel","writeLocalSourceManifest","writeMetadataIndex","yamlScalar","yamlToBlock"],
 llm:["getAdapter","localAdapter","makeOpenAIAdapter","resetAdapter","setAdapter"],
};
describe("public runtime API",()=>{
 for(const [name,value] of Object.entries({root,inventory,schema,advanced,llm})) test(`${name} exact runtime inventory`,()=>expect(Object.keys(value).sort()).toEqual(expected[name as keyof typeof expected].sort()));
 test("root excludes process-global and low-level controls",()=>{ for(const name of ["setAdapter","injectFile","parseCanonicalYaml","buildDedupReport"]) expect(name in root).toBe(false); });
});
