// validation_report.test.ts — a validation report that cannot outlive its tree.
//
// The repository shipped a `VALIDATION_REPORT.md` dated August 2026, recording a
// green gate over 61 suites and 528 tests. By the time it was read the suite had
// more than doubled and the tree had moved many times. Nothing in the file tied
// it to a commit, so it went on answering "is this green" with a yes that had
// been true once — which is worse than having no report at all, because a reader
// has no way to tell the difference.
//
// The replacement is generated by running the gate and recording the exit codes
// it actually returned, and it is bound to a digest of the tree it ran over. This
// file holds the two properties that make that binding worth anything: the digest
// moves when the tree does, and it does not move when the only change is the
// report itself — because a binding invalidated by committing the report would
// be a binding nobody could satisfy, and the workaround for that is always to
// stop checking.
import * as fs from "node:fs";
import * as path from "node:path";
import { describe, expect, it } from "vitest";

const REPO = path.resolve(__dirname, "..");
const REPORT = path.join(REPO, "CURRENT_VALIDATION_REPORT.md");

const reporter = require("../scripts/validation-report.js") as {
  treeState(): { head: string; clean: boolean; digest: string };
  renderReport(
    state: { head: string; clean: boolean; digest: string },
    results: {
      command: string; note: string; exit_code: number; passed: boolean; tail: string;
    }[],
    generatedAt: string,
  ): string;
};

describe("the tree the report is bound to", () => {
  it("is a digest of the tracked content, not of a commit id", () => {
    const state = reporter.treeState();
    expect(state.head).toMatch(/^[0-9a-f]{40}$/);
    expect(state.digest).toMatch(/^sha256:[0-9a-f]{64}$/);
    // Twice in a row over an unchanged tree: the same answer.
    expect(reporter.treeState().digest).toBe(state.digest);
  });

  it("does not move when the report itself changes", () => {
    const before = reporter.treeState().digest;
    const existed = fs.existsSync(REPORT);
    const original = existed ? fs.readFileSync(REPORT, "utf8") : null;
    try {
      fs.writeFileSync(REPORT, "# rewritten by a test\n", "utf8");
      // This is the property that makes the binding usable: generate the report,
      // commit it, and the digest it names is still the digest of the tree. A
      // binding that broke here would be one every contributor learns to skip.
      expect(reporter.treeState().digest).toBe(before);
    } finally {
      if (original === null) fs.rmSync(REPORT, { force: true });
      else fs.writeFileSync(REPORT, original, "utf8");
    }
  });

  it("moves when anything else does", () => {
    const before = reporter.treeState().digest;
    const probe = path.join(REPO, "src", ".validation-report-probe.ts");
    try {
      fs.writeFileSync(probe, "export const probe = 1;\n", "utf8");
      // An untracked file under `src` is exactly the change a stale report would
      // otherwise describe as green.
      expect(reporter.treeState().digest).not.toBe(before);
    } finally {
      fs.rmSync(probe, { force: true });
    }
    expect(reporter.treeState().digest).toBe(before);
  });
});

describe("what the report says", () => {
  const state = { head: "a".repeat(40), clean: true, digest: `sha256:${"b".repeat(64)}` };

  it("records a failure as a failure, with the output that caused it", () => {
    const rendered = reporter.renderReport(state, [
      { command: "npm run lint", note: "ESLint", exit_code: 0, passed: true, tail: "" },
      {
        command: "npm run validate",
        note: "the aggregate gate",
        exit_code: 1,
        passed: false,
        tail: "Tests  3 failed | 1180 passed",
      },
    ], "2026-08-23T00:00:00.000Z");

    // A report generator that could only write "green" would be a formatting
    // exercise. The failing path has to be the one that is exercised.
    expect(rendered).toContain("**RED**");
    expect(rendered).toContain("**FAIL**");
    expect(rendered).toContain("3 failed | 1180 passed");
    expect(rendered).toContain("this tree is not green");
    expect(rendered).not.toContain("**green**");
  });

  it("says green only when every exit code was zero", () => {
    const rendered = reporter.renderReport(state, [
      { command: "npm run lint", note: "ESLint", exit_code: 0, passed: true, tail: "" },
      { command: "npm run validate", note: "the aggregate gate", exit_code: 0, passed: true, tail: "" },
    ], "2026-08-23T00:00:00.000Z");

    expect(rendered).toContain("**green**");
    expect(rendered).not.toContain("**FAIL**");
    expect(rendered).toContain(`\`${state.head}\``);
    expect(rendered).toContain(`\`${state.digest}\``);
    // And it is explicit about what it is not, because the failure this whole
    // mechanism replaces was a report being read as more than it was.
    expect(rendered).toContain("not a publication authorization");
    expect(rendered).toContain("not a statement about any other commit");
  });
});

/**
 * The one run that cannot require the report to exist: the run producing it.
 *
 * `scripts/validation-report.js` runs the suite in order to record what it did,
 * and the suite contains this file. Without this the generating run would fail on
 * the absence of the artifact it is about to write, and the report would record
 * RED for a tree that is green.
 *
 * A stated, narrow, mechanically-scoped exception: one variable, set by the
 * generator and by nothing else, and every other invocation — a contributor's
 * `npm test`, CI, `npm run validate` — is strict.
 */
const generating = process.env.L9_VALIDATION_REPORT_RUN === "1";

describe.skipIf(generating)("the report in this repository", () => {
  it("exists, is bound to this tree, and records a green verdict", () => {
    // The check the script performs, performed here too, so a stale report is a
    // test failure rather than something a contributor has to remember to run.
    expect(fs.existsSync(REPORT), "CURRENT_VALIDATION_REPORT.md is missing").toBe(true);
    const contents = fs.readFileSync(REPORT, "utf8");
    const digest = /\*\*Bound to tree:\*\* `(sha256:[0-9a-f]{64})`/.exec(contents);
    expect(digest, "the report does not name a tree digest").not.toBeNull();
    expect(digest?.[1], "the report describes a different tree; re-run npm run validate:report")
      .toBe(reporter.treeState().digest);
    expect(contents).toContain("**green**");
  });

  it("replaced the unbound report rather than sitting beside it", () => {
    // Two validation reports is one report and one trap, and the trap is
    // whichever one a reader happens to open.
    expect(fs.existsSync(path.join(REPO, "VALIDATION_REPORT.md"))).toBe(false);
  });
});
